package dev.mnascimentos.aureole.feature.settings.model

import androidx.compose.ui.graphics.vector.ImageVector

data class PreferenceItemConfig(
    val title: String,
    val subtitle: String? = null,
    val leadingIcon: ImageVector? = null,
    val enabled: Boolean = true
)

data class SettingsScreenActions(
    val onBackClick: () -> Unit = {},
    val onSetDefaultLauncherClick: () -> Unit = {},
    val onOpenFavoritePickerClick: () -> Unit = {},
    val onToggleShowAllAppsOnHome: () -> Unit = {},
    val onToggleHomeButtonOpensAllApps: () -> Unit = {},
    val onToggleWidgetRow: () -> Unit = {},
    val onToggleContainer: () -> Unit = {},
    val onToggleContainerBackground: () -> Unit = {},
    val onToggleContainerExpandCell: () -> Unit = {},
    val onToggleClockBackground: () -> Unit = {},
    val onToggleShowContainerAddFolderButton: () -> Unit = {},
    val onToggleShowFolderLabels: () -> Unit = {},
    val onOpenContainerPositionDialog: () -> Unit = {},
    val onDismissContainerPositionDialog: () -> Unit = {},
    val onContainerPositionSelected: (String) -> Unit = {},
    val onToggleLeftHandedMode: () -> Unit = {},
    val onToggleDynamicWallpaper: () -> Unit = {},
    val onOpenColorPickerDialog: () -> Unit = {},
    val onSelectManualSeedColor: (Int) -> Unit = {},
    val onSelectTheme: (String) -> Unit = {},
    val onSelectFont: (String) -> Unit = {},
    val onDismissColorPickerDialog: () -> Unit = {},
    val onChangeWallpaperClick: () -> Unit = {},
    val onRestoreDefaultWallpaperClick: () -> Unit = {},
    val onConfirmRestoreWallpaper: () -> Unit = {},
    val onDismissRestoreWallpaperDialog: () -> Unit = {},
    val onClearErrorMessage: () -> Unit = {},
    val onAddFolderClick: () -> Unit = {},
    val onDismissCreateFolderDialog: () -> Unit = {},
    val onSubmitCreateFolder: (String) -> Unit = {},
    val onToggleHaze: () -> Unit = {},
    val onOpenHazeOpacityDialog: () -> Unit = {},
    val onHazeOpacitySelected: (Float) -> Unit = {},
    val onDismissHazeOpacityDialog: () -> Unit = {},
    val onToggleShowWidgetDots: () -> Unit = {},
    val onToggleInAppUpdate: () -> Unit = {},
    val onHeaderOffsetChanged: (Int) -> Unit = {},
    val onToggleThemedAppIcons: () -> Unit = {},
    val onToggleDisableAlphabetScrubber: () -> Unit = {},
    val onOpenResetGridDialog: () -> Unit = {},
    val onConfirmResetGrid: () -> Unit = {},
    val onDismissResetGridDialog: () -> Unit = {},
    val onOpenFactoryResetDialog: () -> Unit = {},
    val onConfirmFactoryReset: () -> Unit = {},
    val onDismissFactoryResetDialog: () -> Unit = {},
    val onToggleShowSettingsButtonInAllApps: () -> Unit = {},
    val onOpenSettingsButtonPositionDialog: () -> Unit = {},
    val onDismissSettingsButtonPositionDialog: () -> Unit = {},
    val onSettingsButtonPositionSelected: (String) -> Unit = {},
    val onToggleShowSearchBarInAllApps: () -> Unit = {},
    val onOpenSearchIconPositionDialog: () -> Unit = {},
    val onDismissSearchIconPositionDialog: () -> Unit = {},
    val onSearchIconPositionSelected: (String) -> Unit = {},
    val onSelectWallpaperScaleType: (String) -> Unit = {},
    val onSelectCornerRadius: (Int) -> Unit = {},
)
