default_platform(:android)

platform :android do
  desc "Build and upload a new internal release to Google Play"
  lane :internal do
    gradle(
      task: "bundleRelease",
      project_dir: "."
    )

    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
